// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEzk1jNR9i7yyLXJVptGpjwWtVr-CYckw',
    appId: '1:1009433484336:web:0b6c0dd3a0034d9b3b21f5',
    messagingSenderId: '1009433484336',
    projectId: 'sves-leave',
    authDomain: 'sves-leave.firebaseapp.com',
    storageBucket: 'sves-leave.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoI1U2saOzE3zFLS3f4Zf5XVS7QGpbGI',
    appId: '1:1009433484336:android:c6c57f72fe5efb403b21f5',
    messagingSenderId: '1009433484336',
    projectId: 'sves-leave',
    storageBucket: 'sves-leave.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXloaXJioUJfqe7tX3s7dpbYo7TELvyKg',
    appId: '1:1009433484336:ios:94be97d7b32d434d3b21f5',
    messagingSenderId: '1009433484336',
    projectId: 'sves-leave',
    storageBucket: 'sves-leave.firebasestorage.app',
    iosBundleId: 'com.example.svesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXloaXJioUJfqe7tX3s7dpbYo7TELvyKg',
    appId: '1:1009433484336:ios:94be97d7b32d434d3b21f5',
    messagingSenderId: '1009433484336',
    projectId: 'sves-leave',
    storageBucket: 'sves-leave.firebasestorage.app',
    iosBundleId: 'com.example.svesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEzk1jNR9i7yyLXJVptGpjwWtVr-CYckw',
    appId: '1:1009433484336:web:cff39f8697020ffb3b21f5',
    messagingSenderId: '1009433484336',
    projectId: 'sves-leave',
    authDomain: 'sves-leave.firebaseapp.com',
    storageBucket: 'sves-leave.firebasestorage.app',
  );
}
